# Nome da nossa automação
name: CI/CD Pipeline Loja Veloz

# Gatilho: Executa sempre que houver um 'push' na branch main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # O robô roda em um servidor Linux do GitHub

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Configurar o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências e validar API Gateway
      run: |
        cd services/api-gateway
        npm install

    - name: Instalar dependências e validar Pedidos
      run: |
        cd services/pedidos
        npm install

    - name: Instalar dependências e validar Estoque
      run: |
        cd services/estoque
        npm install

    - name: Instalar dependências e validar Pagamentos
      run: |
        cd services/pagamentos
        npm install

    - name: Construir imagens Docker (Simulação de Build)
      run: |
        docker build -t bruna/api-gateway:latest ./services/api-gateway
        docker build -t bruna/pedidos:latest ./services/pedidos
        docker build -t bruna/estoque:latest ./services/estoque
        docker build -t bruna/pagamentos:latest ./services/pagamentos